services:
  app-1:
    build: .
    ports:
      - 3001:3000
    container_name: app1
    environment:
      - APP_NAME="App-1"  
    networks:
      - app-network

  app-2:
    build: .
    ports:
      - 3002:3000
    container_name: app2
    environment:
      - APP_NAME="App-2"  
    networks:
      - app-network

  app-3:
    build: .
    ports:
      - 3003:3000
    container_name: app3
    environment:
      - APP_NAME="App-3"  
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app-1
      - app-2
      - app-3
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge